### ISSUE TITLE
BHTOM-TOMTOOLKIT 2024 Workshop planning

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#1010]
Here are some notes from today's meeting with the BHTOM team and my understanding of the plan for the upcoming Crete workshop. 

### Context:
BHTOM2 currently depends on a forked version of the TOM Toolkit, roughly v1.7.  This puts it significantly behind the current Toolkit in terms of functionality that they would like (in particular tom_observations) and so they want to figure out a path for them to upgrade BHTOM to the modern Toolkit, bringing the repos back more in sync.  They have implemented a lot of customizations, in particular broker services, which would benefit other users if the code can be ported into the Toolkit.  BHTOM2 differs from most TOMs in that it has been structured around a microservices model, using Kafka as the internal messaging service.  They want to retain this model of operations. 

**Goal for the end of the Crete workshops is to formulate a roadmap for this upgrade and necessary development.**

### TOM Presentations
The TOM Team should brief the BHTOM group on the most relevant features of the modern Toolkit.  These include:
- [x] #1028
- [x] #1029
- [x] #1030
- [x] #1041
- [x] Walk through the github project board 

### Preparatory work this sprint
- [x] Visit bhtom.space "About" pages and review the API documentation to understand what APIs they need for their microservices.  Diff these with those currently supported by the TOM Toolkit and develop a plan for their implementation
- [x] Review the BHTOM2 repository for their [data harvesters](https://github.com/BHTOM-Team/harvesters-service), develop a plan for integrating these with tom_dataservices.   
- [x] Understand how they use the Toolkit as a library within their microservices.  
- [x] Review their database model.py and document the information they store for individual telescopes and instruments, in order to support the wide range of observatories, most of which are manually operated.  Figure out how to integrate this with TOM's facilities module and plans to store telescope information.

**Comment by rachel3834** [comment]
Here are some notes from today's meeting with the BHTOM team and my understanding of the plan for the upcoming Crete workshop. 

### Context:
BHTOM2 currently depends on a forked version of the TOM Toolkit, roughly v1.7.  This puts it significantly behind the current Toolkit in terms of functionality that they would like (in particular tom_observations) and so they want to figure out a path for them to upgrade BHTOM to the modern Toolkit, bringing the repos back more in sync.  They have implemented a lot of customizations, in particular broker services, which would benefit other users if the code can be ported into the Toolkit.  BHTOM2 differs from most TOMs in that it has been structured around a microservices model, using Kafka as the internal messaging service.  They want to retain this model of operations. 

**Goal for the end of the Crete workshops is to formulate a roadmap for this upgrade and necessary development.**

### TOM Presentations
The TOM Team should brief the BHTOM group on the most relevant features of the modern Toolkit.  These include:
- [ ] Custom Target models (BHTOM has already customized their Targets)
- [ ] TOM's Data Services refactor (and how their data harvesters might fit into this)
- [ ] Status of tom_observations, particularly TOM's ESO facilities module

### Preparatory work this sprint
- [ ] Visit bhtom.space "About" pages and review the API documentation to understand what APIs they need for their microservices.  Diff these with those currently supported by the TOM Toolkit and develop a plan for their implementation
- [ ] Review the BHTOM2 repository for their [data harvesters](https://github.com/BHTOM-Team/harvesters-service), develop a plan for integrating these with tom_dataservices.   
- [ ] Understand how they use the Toolkit as a library within their microservices.  
- [ ] Review their database model.py and document the information they store for individual telescopes and instruments, in order to support the wide range of observatories, most of which are manually operated.  Figure out how to integrate this with TOM's facilities module and plans to store telescope information.
