### ISSUE TITLE
Data harvested from brokers doesn't have assigned Data Product

### ISSUE THREAD

**Issue by KKruszynska** [TOMToolkit/tom_base#1122]
Currently, if a harvester downloads data into a TOM Toolkit-based system, the data points are stored as a ReducedDatum, but they don't have a linked Data Product. This is not the case if the user uploads the data. It is necessary for data sharing with the collaborators (for example, if there is Gaia data in my TOM, I cannot share it easily with the others through the Target page) and for efficiently fitting microlensing events tracked by MOP.

**Comment by jchate6** [comment]
Hi @KKruszynska, we have hesitated to automatically create data products associated with the results of a broker query because as data comes in, the same query can generate different results each time. This could result in "overlapping" data products that contain mostly the same information with a few extra data points each time. 

The preferred way to share data is to use the sharing options at the bottom of the photometry tab to upload data to Hermes, download data to a csv, or directly via the API of another TOM.
![image](https://github.com/user-attachments/assets/358ff3e2-1ea9-4a79-a372-effec0b02465)

Alternatively you can share the entire target and any of its data from the "share" button under the target name on the target detail page:
![image](https://github.com/user-attachments/assets/d4fc8527-dbb1-4ac3-8d88-a0f8aa2b36e5)

I understand that this can be clunky with the current tables. We are working on adding filtering, pagination and sorting to these tables to make them more useful. see
 - #1111 

If filtering out specific data points because they have already been shared is too cumbersome, it should be safe to share all the photometry data with another TOM and it should only ingest new data.

If you are sharing the data with a collaborator who doesn't have a TOMToolkit TOM, then hopefully the Download option should be what you need.

If you are trying to share spectroscopy, or any of the above features are not present in MOP, or are giving you trouble, let me know and I can help sort them out.

**Comment by rachel3834** [comment]
Many thanks for explaining @jchate6 - I agree that reasoning makes sense for data that routinely updates.    
The data sharing tools are a good way of manually downloading the data.  
I'll close this thread because what we now think we actually need is an API, but that's a different issue....
