### ISSUE TITLE
Calculate GST for EVN

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#1129]
Discussions with the Opticon/Radionet Pilot group raised the question of submitting a single observation request to a network of facilities either through a single call to a single portal or through multiple portals.
Due to the way the scheduling system for radio facilities calculates GST, the discussion concluded that the observational request should include a user's requested date range which each facility can then interpret and schedule the observations at a suitable GST interval.

Action for the TOM team is to evaluate whether this is a viable modification to our observation request schema.

**Comment by rachel3834** [comment]
Discussions with the Opticon/Radionet Pilot group raised the question of submitting a single observation request to a network of facilities either through a single call to a single portal or through multiple portals.  
Due to the way the scheduling system for radio facilities calculates GST, the discussion concluded that the observational request should include a user's requested date range which each facility can then interpret and schedule the observations at a suitable GST interval.  

Action for the TOM team is to evaluate whether this is a viable modification to our observation request schema.

**Comment by jchate6** [comment]
For reference:
GST = "Greenwich Sidereal Time"
This is the current Sidereal Time at the Prime Meridian (also used to determine UTC) as opposed to:
LST = "Local Sidereal Time"
The Current Sidereal Time at the local Meridian.

Sidereal Time = The Hour angle of the equinox. This is the equivalent of the RA passing directly over head at the reference location.
This is a standard and useful unit of measurement since it lets Astronomers easily reference what is currently visible from a given location. Effectively a sidereal day is how long it takes the earth to rotate with respect to the stars, and a standard (solar) day is how long it takes to rotate with respect to the Sun. This makes a sidereal day ~4min shorter than a solar day because the Earth has moved in it's orbit over the course of that day and needs to rotate just a little bit further to point the same meridian back to the sun.

There are [astropy methods](https://docs.astropy.org/en/latest/time/index.html#sidereal-time-and-earth-rotation-angle) for figuring this out. And it should not be difficult to incorporate such a field in a facility.

**Comment by jchate6** [comment]
Yes, this could be handled in multiple ways.
The EVN facility would have its own fields and submission methods.

We could have a standard date picker that converts the values into GST using astropy before submission or we could simply have a field where users enter the GST directly depending on how complex we want the form and how spicy we are feeling.
