### ISSUE TITLE
Target/Extra in admin does not allow for empty values

### ISSUE THREAD

**Issue by wyrzykow** [TOMToolkit/tom_base#228]
**Describe the bug**
When editing my db in /admin/ zone for Target-Extra fields, I am not allowed to SAVE without setting any value to all fields, even if they were empty before. This works in TOM in Create or Update, where I can leave those fields with empty value, but in admin. 
This could be django thing actually.

**To Reproduce**
Go to /admin/
Targets
select any target and scroll down to the extra fields.
You need a new field which has no value defined. 
If you click SAVE, django gives and error as shown in the screenshot.

**Expected behavior**
If the field value was not previously defined, leave it undefined at Save.

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome
 - TOM 1.2.3
 - Python Version 3.7.1

![image](https://user-images.githubusercontent.com/26644157/70483083-4d296400-1a9c-11ea-9114-749fe6af54e7.png)

**Comment by dmcollom** [comment]
@wyrzykow I'm not sure this is a bug--to be clear, there are two types of extras.

1. Extras as defined in `EXTRA_FIELDS` in `settings.py`. A defined `EXTRA_FIELD` creates a field in the Target create and update forms, that can be left blank.
2. Extras NOT defined in `EXTRA_FIELDS`, also known as "tags", _must_ have a value, or be deleted. Otherwise it doesn't really make sense if they exist at all.

I can't see your db, but I'm assuming that `ztf_alert_name` is **not** defined in `settings.py` as an `EXTRA_FIELD`, would that be correct? Or is it defined as such?

**Comment by wyrzykow** [comment]
Hi David,

I realised there are two sets of extras, but I am only using those set in settings. ztfname is set in settings. 

cheers,

Łukasz from the phone

**Comment by dmcollom** [comment]
So I suspect that it doesn't save the "no value" in either case, it just happens to pass validation in the non-admin view. This is a result of the implementation--we _might_ be able to work a fix in, but I don't want to promise anything. Is it something you feel is essential?

**Comment by dmcollom** [comment]
Having discussed this with Lukasz, I think it's safe to say that a field should be able to be cleared without resorting to the admin interface. Tagging this as a bug.

**Comment by Fingel** [comment]
This was addressed in https://github.com/TOMToolkit/tom_base/commit/9eb071de4daeede809f87648bce1d87687474a1d and will be fixed in the next release.
