### ISSUE TITLE
'TypeError: Can't Instantiate abstract class' when trying to create observation module

### ISSUE THREAD

**Issue by jlibermann** [TOMToolkit/tom_base#287]
**Describe the bug**
I'm following the TOM toolkit documentation to create an observation module, but I'm getting a TypeError when I try to view a target in my TOM.

**To Reproduce**
1. Create `myfacility.py` file with observation facility classes copied and pasted in.
2. Update `settings.py` with new observation facility class.
3. Reload TOM and click on target.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Browser: chrome
- Python Version: 3.8.3

**Comment by dmcollom** [comment]
Hi @jlibermann,

Sorry you're running into this. Can you paste either a screenshot of the error or the full stack trace so that we can have a little bit more information on this? Thanks!

**Comment by jlibermann** [comment]
I attached a screenshot:
![Screenshot from 2020-06-23 18-20-40](https://user-images.githubusercontent.com/65671429/85471354-5680a680-b57e-11ea-8fe6-b82dd3145400.png)

**Comment by dmcollom** [comment]
So, it looks like at least one of those eight methods that are mentioned in the error message is missing from your custom facility. Just as a test, I created a new facility in a new TOM, and pasted in the code listed in this tutorial: https://tom-toolkit.readthedocs.io/en/stable/observing/observation_module.html. I was able to load my target page without issue, which makes me think there's a missing method.

Can you paste the code from your Panoptes Facility file here, or link to your repo?

**Comment by jlibermann** [comment]
I pasted my code below:
`from tom_observations.facility import BaseRoboticObservationFacility, BaseRoboticObservationForm


class PanoptesObservationFacilityForm(BaseRoboticObservationForm):
    pass


class PanoptesObservationFacility(BaseRoboticObservationFacility):
    name = "PANOPTES"
    observation_types = [("OBSERVATION", "Custom Observation")]

    def data_products(self):
        return

    def get_form(self, observation_type):
        return PanoptesObservationFacilityForm`

**Comment by jlibermann** [comment]
I added in all the methods, and it's working now. Thanks!

**Comment by dmcollom** [comment]
Ah, I think I understand.

So, `BaseRoboticObservationFacility` is an abstract class, with 8 abstract methods. An abstract method has no parent implementation, but is required to be implemented by a subclass (in this case, `PanoptesObservationFacility`). The tutorial example at that point mentions this, and shows examples of how to minimally implement the first two abstract methods, but doesn't show all of them, which is why your facility is throwing an exception. We'll definitely make the documentation clearer that this is just the start of the example, and not all of it.

In the meantime, a little lower down in the tutorial is the "full" implementation (the bare minimum while still able to run). Here it is for reference:

```
from tom_observations.facility import BaseRoboticObservationFacility, BaseRoboticObservationForm

class MyObservationFacilityForm(BaseRoboticObservationForm):
    exposure_time = forms.IntegerField()
    exposure_count = forms.IntegerField()

class MyObservationFacility(BaseRoboticObservationFacility):
    name = 'MyFacility'
    observation_types = [('OBSERVATION', 'Custom Observation')]

    def data_products(self, observation_id, product_id=None):
        return []

    def get_form(self, observation_type):
        return MyObservationFacilityForm

    def get_observation_status(self, observation_id):
        return ['IN_PROGRESS']

    def get_observation_url(self, observation_id):
        return ''

    def get_observing_sites(self):
        return {}

    def get_terminal_observing_states(self):
        return ['IN_PROGRESS', 'COMPLETED']

    def submit_observation(self, observation_payload):
        print(observation_payload)
        return [1]

    def validate_observation(self, observation_payload):
        pass
```

So if you add those implementations, your facility should work! Let me know if this works or if you experience any further issues.

**Comment by dmcollom** [comment]
Looks like you beat me to it!
