### ISSUE TITLE
'NoReverseMatch' Error When Attempting to Add a Page to the Navbar

### ISSUE THREAD

**Issue by jlibermann** [TOMToolkit/tom_base#289]
**Describe the bug**
Hi, I'm attempting to link a view that I wrote in a separate app to the navbar, but I keep getting a `NoReverseMatch` error. I'm not sure what the issue is, as I've made sure that my urls are properly namespaced. 
 **To Reproduce**
1. Run the server
2. See error

**Screenshots**

![Screenshot from 2020-07-14 11-45-34](https://user-images.githubusercontent.com/65671429/87447419-914b8c80-c5c8-11ea-9baa-51f029ff10a1.png)

**Desktop (please complete the following information):**
- OS: [Ubuntu 20.04]
- Browser [chrome]
- Python Version [3.8.3]

**Additional context**

**Comment by dmcollom** [comment]
Hi @jlibermann,

On a cursory glance, it looks like the `slug` might be an argument rather than a keyword argument in a template--that is:

```
    <a class="nav-link" href="{%url 'remoterequests:profile-view' slug %}" style="color:black">Remote Requests</a>
```

So, `slug` rather than `slug=slug`, assuming that `slug` is readily available in the template context.

Hopefully this helps, but if my suspicions are incorrect, please include either a link to the relevant bits of code or at least snippets of code in the issue.

**Comment by jlibermann** [comment]
Hi, in trying to diagnose the error, I've noticed that the `NoReverseMatch` message is the same regardless of what arguments I provide. I attached the relevant bits of code in my `views.py` and `urls.py` files for more context.

`views.py`:

https://github.com/jlibermann/panoptes-tom/blob/6e473612f70d849580e28ba56b24c0e713081675/panoptes_tom/remoterequests/views.py#L75-L107

`urls.py`:

    path(
        "remoterequests/<slug>", profile_view, name="profile-view"
    ),  # TODO: Consider renaming slug

**Comment by dmcollom** [comment]
Alright, I cloned your repo and I now see what's going on.

The `slug` isn't available in the context of every page--however, because your `Profile` model has a one-to-one relationship with the `User` model, you can access the slug in the template by way of: `user.profile.slug`. The logged-in `user` is always available in the context, so it should be accessible in all views, which is essential because you're putting this url in the navbar.

**Comment by jlibermann** [comment]
Thank you that worked! Now I just have to figure out how to set the slug when the `user` is not logged in as that also gives a `NoReverseMatch` error.

**Comment by dmcollom** [comment]
No worries! And you can probably put a check in to only render the nav item if the user is not AnonymousUser. We've got an example here: https://github.com/TOMToolkit/tom_base/blob/4132fef020ca7b2c5ef246ff246277afbd3c2ccc/tom_common/templates/tom_common/base.html#L48
