### ISSUE TITLE
Python dict not showing up in db

### ISSUE THREAD

**Issue by jlibermann** [TOMToolkit/tom_base#292]
**Describe the bug**
I'm trying to add an additional Python dict, `target_fields`, to my `ObservationRecord` model, but it's not showing up in my db. I'm not sure what I could be doing wrong here. 
**To Reproduce**
1. Submit observation via observation form. 
2. Query `observationrecord` in db
3. `target_fields` doesn't appear

**Screenshots**
My `facility.py` file:
![Screenshot from 2020-07-27 12-41-37](https://user-images.githubusercontent.com/65671429/88568295-beeff700-d006-11ea-8dd9-2a9e9d841fb2.png)

My `models.py`:
![Screenshot from 2020-07-27 12-47-08](https://user-images.githubusercontent.com/65671429/88568670-535a5980-d007-11ea-9e49-4bc3e82ab774.png)

**Desktop (please complete the following information):**
- OS: [Ubuntu 20.04]

- Python Version [e.g. 3.8.3]

**Comment by dmcollom** [comment]
Hi @jlibermann, sorry you're running into this. The reason it isn't saving is because the `ObservationCreateView.form_valid()` method is where the actual saving happens. Specifically here: https://github.com/TOMToolkit/tom_base/blob/4132fef020ca7b2c5ef246ff246277afbd3c2ccc/tom_observations/views.py#L249

I'm curious what your objective here is and if we can't identify a smoother way to implement it. Is there a particular reason you're saving the target fields on the `ObservationRecord` rather than just referencing the `Target` itself? If this is an `lco.py` submission, the `Target` parameters are submitted as well, so you'll still have a record of them on the `ObservationRecord`. I'm also curious as to why you're putting this in the `facility.py` interface rather than the facility-specific module.

If you're dead set on this particular approach, you'll need to create a custom view that inherits from `tom_observations.views.ObservationCreateView`, override the `form_valid()` method, and do a little url routing in your `urls.py`, but unless it's absolutely necessary, I would advise against it, as it's introducing additional complexity.

**Comment by jlibermann** [comment]
Hi, sorry I wasn't specific enough. My `ObservationRecord` actually is in a facility-specific module called `pan012.py` not `facility.py`. This is not an `lco.py` submission but rather a submission for our particular facility. My goal was to query target-specific information such as RA and Dec for each submitted observation, but I realized that I can accomplish that simply by querying from the `tom_targets_targetname` table.
