### ISSUE TITLE
Support cadence generation for LCO observations

### ISSUE THREAD

**Issue by Fingel** [TOMToolkit/tom_base#44]
The LCO observation module should support requesting cadence observations. 

Currently LCO handled cadences by generating a series of requests. This would show up as a large amount of observation requests within the TOM. It's unclear that this would be desirable.

**Comment by rachel3834** [comment]
So I think there are two parts to this.  

**Info on large numbers of subrequests**
Some existing TOMs (such as the microlensing one) store all the subrequests associated with a given cadence request.  Anyone asking for a cadence request cares that each subrequest is executed, so whether or not each one was can be assumed to be of interest to the user.  

That said yes it could potentially be quite a lot of information to display.  What we do is associate the subrequests with a request object, and then choose to display/calculate with the requests or subrequests as needed.  

So for example, in the list of observation requests on the target page, I display just the main request rather than the subrequests.  You could imagine adding a link to the observation in Valhalla so the user could access a display of the subrequests if they want.  But I have some software which uses the information on the subrequests to determine at what rate the subrequests are being completed.  That's something I know NEOEx also calculates because users need to know their observing efficiency to determine how best to use their observing time.  

**Handling cadence behaviour**
Some science cases demand time-variable cadence (SNe, microlensing, outbursts...), and it any case users will want to review the target's behaviour and the data obtained so far when they decide what observations to do next.  
I consider that to be a fairly advanced use, because to first order users can control this by submitting a cadence observation, waiting for it to complete, assessing the results, then submitting subsequent results with different parameters if they need to.  If the TOM's "simple obs form" can request just a simple cadence for a single request, that is fine - and users who want more complex behaviour will ultimately be able to do so using the programmatic interfaces.

**Comment by dmcollom** [comment]
As was determined in the TOM science meta-planning meeting, the first stage should be proactive generation of simple linear cadences, potentially expanding to multiple distributions of cadencing.

1. Expand the data model to track cadences.
2. Expand the facility interface to add a method for cadence generation
3. Add period and jitter to the LCO and SOAR observing forms.
4. Implement cadence generation in appropriate facility modules, including cadence saving.
5. Add confirmation view showing a plot of the request windows over time.
6. Expand observation status updates to support cadenced observations.
7. Update views referring to observations to support cadenced observations.
8. (stretch goal) Add observation distribution function support.
9. (stretch goal) Plot target visibility over cadence plot.
10. (stretch goal) Allow interactive adjustment of cadence windows prior to submission.

This list is likely incomplete, but this feature will be addressed in the upcoming sprint from 11/19-12/17.

**Comment by dmcollom** [comment]
This was addressed by #232 and #249 and released in 1.3.1.
