### ISSUE TITLE
Authentication should redirect to previous page

### ISSUE THREAD

**Issue by dmcollom** [TOMToolkit/tom_base#54]
When trying to access TOM functionality that requires a login, the TOM redirects to a login page. Upon submitting login credentials, the TOM redirects to the homepage.

Redirection should instead go to the page that the user was attempting to access before needing to authenticate.

**Comment by dmcollom** [comment]
Added in #57

**Comment by dmcollom** [comment]
On pages that, after authorization, would redirect to a previous page, the redirection goes to the login page. Example:

When unauthenticated, click on a data product tag to change it. Log in. Modify the tag. Upon saving the new tag, the page redirects to login again. This should be corrected.

**Comment by Fingel** [comment]
@dmcollom I think this is because you were using referer = urlparse(referer).path if referer else '/' (https://github.com/TOMToolkit/tom_base/commit/8600be2821d566ced9085861a43ec9383592e50a#diff-6b72e1aaa34a72d73096611d84ba0eafL72) instead of redirecting back to a fixed url (i.e. the target detail page). Hopefully this pattern isn't elsewhere, and since we've removed the ability to change tags altogether, I'm going to close this issue.
