### ISSUE TITLE
Review Lasair broker module to ensure compatibility with upgraded service

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#620]
**Is your feature request related to a problem? Please describe.**
An email from the operators of the Lasair alert broker indicates that they are planning substantial upgrades.  

Assiging this to Lindy in the first instance for triage.  Please feel free to reassign as appropriate. 

**Describe the solution you'd like**
We need to review the TOM Toolkit's lasair module and check that it remains compatible. 

**Additional context**
Email from the Lasair team:

> To all Lasair users
Next week there will be a major upgrade of the Lasair system, starting Tuesday March 14 at 13:00 UTC. We expect the upgrade will take up to 48hrs and the Lasair platform will be unavailable during that time. Please plan for this downtime if you need to access your data during that time.
It is a complete rebuild of the website, comprehensive documentation on readthedocs, and many improvements to the backend data loading. We hope you feel it is an improvement.
The URL will be the same: https://lasair-ztf.lsst.ac.uk/
We expect that all public ZTF alerts will be available in the new system, going back to 2018, as well as user accounts, stored filters (previously queries), stored watchlists, and stored watchmaps (previously area).
From the Lasair Team
Gareth Francis, Andy Lawrence, Terry Sloan, Stephen Smartt, Ken Smith, Roy Williams, Dave Young

**Comment by jchate6** [comment]
From Manisha:
I am working with SAGUARO group and trying to run Lasair query in the SAGUARO TOM. This part of the code should be in: https://github.com/TOMToolkit/tom_base/blob/dev/tom_alerts/brokers/lasair.py
From what I have seen, it looks like the sql query in the TOM doesn't allow me to call things like Sherlock classification that is available in Lasair. Is there some way to add additional query information that is used in Lasair? Here is a sample query I am trying to run:
objects.objectId=sherlock_classifications.objectId AND objects.objectId=watchlist_hits.objectId AND watchlist_hits.wl_id=1 AND watchlist_hits.name=crossmatch_tns.tns_name AND sherlock_classifications.classification not in ("VS", "BS", "CV", "AGN") AND objects.ncandgp > 1 AND objects.jdmin > JDNOW() - 45 AND objects.g_minus_r < 0.5 AND ((objects.dmdt_r < -0.25) OR (objects.dmdt_g < -0.25) OR (objects.dmdt_r > 0.25) OR (objects.dmdt_r > 0.25)) AND ((objects.dmdt_r_err < 0.1) OR (objects.dmdt_g_err < 0.1)) AND objects.objectId NOT LIKE "ZTF17%" AND objects.objectId NOT LIKE "ZTF18%" AND objects.objectId NOT LIKE "ZTF19%" AND objects.objectId NOT LIKE "ZTF20%" AND objects.objectId NOT LIKE "ZTF21%" AND objects.objectId NOT LIKE "ZTF22%"

**Comment by jchate6** [comment]
Additionally, the link to [Lasair website](https://lasair-ztf.lsst.ac.uk/api) on the Lasair Query Form is broken.

**Comment by ms1228** [comment]
Writing to check if there has been any progress with this issue or if there is something I could do to include other query criteria from Lasair into TOM.

**Comment by jchate6** [comment]
Hi @ms1228, I'm working on an audit of our broker functionality right now to make sure we are up to date and everything is functioning. Unfortunately, adding additional functionality such as more complex queries might be outside the scope of my current efforts, but hopefully we can address this soon.

Right now, the only table we search is the `objects` table. Your query includes references to both the `sherlock_classifications` and the `crossmatch_tns` tables. If you are up for it, and want to give us a hand, we would really appreciate it if you could help us add the functionality we're missing to [lasair.py](https://github.com/TOMToolkit/tom_base/blob/dev/tom_alerts/brokers/lasair.py) and make a Pull Request. 

There is a [description](https://lasair.readthedocs.io/en/main/core_functions/rest-api.html#--api-query-) of how to use the query API and a [full list of schema](https://lasair-ztf.lsst.ac.uk/schema/) that can be used in the query.

If this is something you'd like to take on, let me know and I can help, otherwise I'll keep you updated as we finish up our current projects.

Thank you!
