### ISSUE TITLE
What is the role of the Anonymous User?

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#633]
**Describe the bug**
When a TOM is created, an Anonymous User is created by default.  Attempts to edit the account information for this user produce an error that reports that the user already exists.  If the user is removed via the admin interface, it appears again when the server is restarted.  This suggests there may be a key role for this user but this is not explained in the TOM user documentation, which is causing confusion for TOM administrators.  

**Expected behavior**
The role of the Anonymous User, and any constraints on a TOM administrator's ability to edit or remove it, should be described in the TOM documentation.

**Comment by jchate6** [comment]
[Django-Guadians](https://django-guardian.readthedocs.io/en/stable/configuration.html) creates and uses `AnonymousUser` as kind of default, no permissions user to determine what someone who isn't logged in will experience.

It can be renamed, I believe, but we should definitely include an explanation in the docs.

**Comment by phycodurus** [comment]
Generally, Django receives requests, routes them to a View, and returns responses ([ref](https://docs.djangoproject.com/en/4.2/ref/request-response/#module-django.http)).
On the way to a View, [HttpRequest](https://docs.djangoproject.com/en/4.2/ref/request-response/#httprequest-objects) objects pass through a list of Middleware, which can modify the request.
Likewise, responses ([HttpResponse](https://docs.djangoproject.com/en/4.2/ref/request-response/#httprequest-objects) objects) pass from the View back through the list of Middleware (going the opposite direction, if you will).

This list of Middleware is the `settings.py` `MIDDLEWARE` and in that list you'll see `django.contrib.auth.middleware.AuthenticationMiddleware`.
[AuthenticationMiddlware]('django.contrib.auth.middleware.AuthenticationMiddleware',)  adds the `user` attribute to the `HttpRequest` object as it passes through. From the [docs](https://docs.djangoproject.com/en/4.2/topics/auth/default/#authentication-in-web-requests): If the current user has not logged in, this attribute will be set to an instance of [AnonymousUser](https://docs.djangoproject.com/en/4.2/ref/contrib/auth/#django.contrib.auth.models.AnonymousUser), otherwise it will be an instance of [User](https://docs.djangoproject.com/en/4.2/ref/contrib/auth/#django.contrib.auth.models.User).

And, yes, we should explain this in an appropriate place in the documentation.

**Comment by jchate6** [comment]
But that's just a instance of an `AnonymousUser` object. I assume the  `AnonymousUser` that Tom users are confused about is the one that shows up in the DB. That one is created by Django-Guardians.
![image](https://user-images.githubusercontent.com/32683393/233437764-62fd0b00-db35-47b4-8fcb-5a5449eb85ce.png)
