### ISSUE TITLE
TOM-TOM Direct Data Sharing

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#641]
As a TOM user with collaborators with their own TOMs, I want to be able to directly share information between our TOMs.

Things I would want to share:

- [x] DataProducts (#643 )
- [x] ReducedDatums (#642 )
- [x] Targets (#644 )
- [x] TargetLists (#645 )
- [ ] NonLocalizedEvents?

**Comment by rachel3834** [comment]
The highest priorities for direct sharing are the first three I think.  I
can see value in sharing non-localised events but I imagine that raises
some complex questions (e.g. do you then share all associated candidates as
well?).  Since the Hermes platform is designed with this user-base in mind,
and already in operation, I suggest starting with the first three.

For reference, I'm including here some information on the use cases from
two existing TOM teams for this functionality.



Microlensing TOM Data Sharing Use-cases

Purpose

Description of use-cases for sharing information between TOM systems used
for microlensing observations

Context

Both BHTOM and MOP have been built with the TOM Toolkit, but customized
independently.

The teams are in communication via a shared Slack workspace.

Use-cases

   1. Sharing Targets

Both TOMs have automated processes that harvest targets from different
brokers, with different selection criteria.  As a result, one TOM will
sometimes ingest a Target that the other TOM doesn’t know about.  The TOMs
are configured with similar EXTRA_PARAMs for each target, which describe
the parameters of the theoretical model for the event lightcurve.  However,
these EXTRA_PARAMs may be declared with different key labels e.g. “u0” in
TOM1 may be called “u_o” in TOM2.
Manual sharing of targets:

Team members communicate via Slack and realise that a Target in TOM1 is not
known to TOM2.  A team member with an existing account on TOM1 would like
to navigate to the Target page for the event in question, and click a
button to send information about the Target to TOM2.  The information to be
sent should include:

   -

   Target names for the event
   -

   Target RA, Dec
   -

   EXTRA_PARAMs associated with the Target in TOM1

Upon receiving this information, TOM2 will need to map the EXTRA_PARAMs key
names to the corresponding key names within its own EXTRA_PARAMs.

   1. Publish TargetList

Each TOM should provide an API which can be queried by a pre-authenticated
external user and which returns a TargetList in JSON format.  The external
query should specify the identifier for the TargetList to be shared, and
the returned JSON data should have the following schema:

{‘target_list_name’: <listname>,

 ‘Target_list’: {‘target_names’: [‘name1’,’name2’,’name3’,...],

‘ra_deg’: <float>,

‘dec_deg’: <float>,

‘extra_params’: {‘param1’: <value>,

  ‘param2’: <value>,

…}

}

}

Where extra_params is a dictionary of the extra parameters declared in the
TOM publishing the TargetList.

Note that while this use-case requires only sidereal targets, to be fully
general a TOM configured for non-sidereal targets should publish orbital
elements instead of RA, Dec.

The TOM Toolkit may include a harvester function capable of ingesting a
TargetList in this format, when provided with a URL to the publishing TOM.
This harvester will also have to handle the mapping of parameter key names.

   1. Sharing Data Products

Manual sharing of uploaded data files

The teams would like to share their reduced data products between the
TOMs.  These include uploaded CSV files of timeseries photometry and
spectra.

A user of TOM1 would navigate to the Manage Data tab of the TargetView for
a given Target, and click a ratio button to select which data products to
share.  It should be possible to select TOM2 from a list of pre-configured
(and authorised) destinations.

TOM2 should be pre-configured to automatically accept data products from
TOM1 for targets that are already known to TOM1.  It will need to associate
the data products with the appropriate Targets based on the names provided.

If the target cannot be matched based on the names, a new Target should be
created in TOM2, and the data products associated with that.
Download of data from alerts to local files

Both TOMs typically ingest timeseries photometry data from alert providers,
but these are normally stored as ReducedDatums within both TOMs, which
means that the photometry cannot currently be downloaded to a user’s local
disk for further analysis.

Both teams would like to be able to navigate to the Manage Data tab for a
given Target, and select alert data products from the table, and click a
button to download the timeseries data from a given alert provider to a CSV
file.  A user prompt can be used to give the user the opportunity to input
a path and filename on their local system.
